# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.0.dev8+g8fa4e0d.d20230919'
__version_tuple__ = version_tuple = (0, 1, 0, 'dev8', 'g8fa4e0d.d20230919')
